apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aymen-2
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: app/
    repoURL: 'https://github.com/Aym3nTN/argocd-pullrequest-generator-test'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
